Update update-checker.yml

diff --git a/.github/workflows/update-checker.yml b/.github/workflows/update-checker.yml
--- a/.github/workflows/update-checker.yml
+++ b/.github/workflows/update-checker.yml
@@ -1,14 +1,3 @@
-#
-# Copyright (c) 2019-2021 P3TERX <https://p3terx.com>
-#
-# This is free software, licensed under the MIT License.
-# See /LICENSE for more information.
-#
-# https://github.com/P3TERX/Actions-OpenWrt
-# File: .github/workflows/update-checker.yml
-# Description: Source code update checker
-#
-
 name: Update Checker
 
 env:
@@ -29,7 +18,25 @@ jobs:
     - name: Get Commit Hash
       id: getHash
       run: |
-        git clone --depth 1 $REPO_URL -b $REPO_BRANCH .
+        retry() {
+          local n=1
+          local max=5
+          local delay=5
+          while true; do
+            "$@" && break || {
+              if [[ $n -lt $max ]]; then
+                ((n++))
+                echo "Retrying ($n/$max)..."
+                sleep $delay;
+              else
+                echo "The command failed after $n attempts." >&2
+                return 1
+              fi
+            }
+          done
+        }
+
+        retry git clone --depth 1 --branch $REPO_BRANCH --single-branch --filter=blob:none $REPO_URL .
         echo "::set-output name=commitHash::$(git rev-parse HEAD)"
 
     - name: Compare Commit Hash
